name: play-deals-backend 1.0 CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Build Project with Gradle
        uses: gradle/gradle-build-action@v2

      - name: Lint
        run: ./gradlew ktlintCheck

      - name: Tests
        run: ./gradlew :shared:testReleaseUnitTest

